[package]
name = "mison"
version = "0.1.0"
authors = ["Yusuke Sasaki <y_sasaki@nuem.nagoya-u.ac.jp>"]

[dependencies]
simd = "*"
itertools = "*"
num = "*"
error-chain = "*"

[dev-dependencies]
maplit = "*"
