[package]
name = "mison"
version = "0.1.0"
authors = ["Yusuke Sasaki <y_sasaki@nuem.nagoya-u.ac.jp>"]

[dependencies]
num = "*"
error-chain = "*"

simd = { version = "*", optional = true }

[dev-dependencies]
maplit = "*"

[features]
default = []
simd-accel = ["simd"]
